DELETE FROM USER;

INSERT INTO USER (USERNAME, PASSWORD, USER_STATUS, FIRST_NAME, LAST_NAME, ADDRESS, EMAIL, PHONE_NUMBER) VALUES ('testEmployee', '179AD45C6CE2CB97CF1029E212046E81', 'Employee', 'Jan', 'Kowalski', 'Test Address 1/1', 'test1@example.com', '111222333');

INSERT INTO USER (USERNAME, PASSWORD, USER_STATUS, FIRST_NAME, LAST_NAME, ADDRESS, EMAIL, PHONE_NUMBER) VALUES ('testCustomer', '841C4221C2E7E0CEFBC0392A35222512', 'Customer', 'Piotr', 'Nowak', 'Test Address 1/2', 'test2@example.com', '444555666');

DELETE FROM WAREHOUSE_ITEM;

INSERT INTO WAREHOUSE_ITEM (ITEM_NAME, ITEM_TYPE, ITEM_DESCRIPTION, QUANTITY, PRICE) VALUES ('Bottled Water', 'Food', 'Bottled Water', 20, 1.50);

INSERT INTO WAREHOUSE_ITEM (ITEM_NAME, ITEM_TYPE, ITEM_DESCRIPTION, QUANTITY, PRICE) VALUES ('Chicken', 'Food', 'Chicken', 55, 3.75);

INSERT INTO WAREHOUSE_ITEM (ITEM_NAME, ITEM_TYPE, ITEM_DESCRIPTION, QUANTITY, PRICE) VALUES ('Leather Jacket', 'Clothes', 'Leather Jacket', 15, 25.0);

INSERT INTO WAREHOUSE_ITEM (ITEM_NAME, ITEM_TYPE, ITEM_DESCRIPTION, QUANTITY, PRICE) VALUES ('TV', 'Electronics', 'TV', 5, 250.0);

INSERT INTO WAREHOUSE_ITEM (ITEM_NAME, ITEM_TYPE, ITEM_DESCRIPTION, QUANTITY, PRICE) VALUES ('Plastic Chair', 'Furniture', 'Plastic Chair', 40, 12.0);

--DELETE FROM DELIVERY;

--INSERT INTO DELIVERY (EMPLOYEE_ACCEPTING_ID, CUSTOMER_ORDERING_ID, DELIVERY_ADDRESS, DELIVERY_STATUS, OVERALL_PRICE, IS_PAID) VALUES (1, 2, 'Test Address 1/2', 'Completed', 65.0, TRUE);

--DELETE FROM DELIVERY_ITEM;

--INSERT INTO DELIVERY_ITEM (DELIVERY_ID, ITEMS_ORDERED, WAREHOUSE_ITEM_ID) VALUES (1, 10, 1);

--INSERT INTO DELIVERY_ITEM (DELIVERY_ID, ITEMS_ORDERED, WAREHOUSE_ITEM_ID) VALUES (1, 2, 3);